name: Delete view_count.txt Every Half Hour

on:
  schedule:
    - cron: "0,30 * * * *"
  workflow_dispatch:

jobs:
  delete_file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Delete view_count.txt if it exists
      run: |
        if [ -f view_count.txt ]; then
          rm view_count.txt
          echo "view_count.txt deleted."
        else
          echo "view_count.txt does not exist, skipping deletion."
        fi

    - name: Commit and push changes if any
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "Deleted view_count.txt via GitHub Actions"
        else
          echo "No changes detected, pushing empty commit."
          git commit --allow-empty -m "Scheduled run with no file changes"
        fi
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}